### ISSUE TITLE
Include Logging

### ISSUE THREAD

**Issue by tyjkass** [vipra-uwf/VIPRA#12]
For general development, debugging, and error display, it will be helpful to include logging with multiple logging levels. These levels should be set based on the compiled version of the code, e.g. release should have its logging level set to ERROR or WARN, debug should have its logging level set to DEBUG, etc.

**Comment by GoodenoughR** [comment]
8192708 adds basic logging.

More options for file logging etc need to be added

**Comment by GoodenoughR** [comment]
issue #34 addresses this
